# Generated by Django 5.2.17 on 2026-08-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Affordax', max_length=80)),
                ('descriptor', models.CharField(default='Affordability and payroll, connected', max_length=140)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('portal_url', models.URLField(default='https://portal.example.com')),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('partnerships_email', models.EmailField(default='partners@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('office', models.CharField(default='Lilongwe, Malawi', max_length=140)),
                ('linkedin_url', models.URLField(blank=True)),
                ('primary_colour', models.CharField(default='#ef5b3f', max_length=7)),
                ('ink_colour', models.CharField(default='#17202a', max_length=7)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
