# Generated by Django 5.2.17 on 2026-08-24 20:10

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('audience_label', models.CharField(max_length=60)),
                ('hero_title', models.CharField(max_length=150)),
                ('hero_text', models.TextField(max_length=440)),
                ('action_label', models.CharField(max_length=50)),
                ('action_url', models.CharField(max_length=240)),
                ('body', wagtail.fields.StreamField([('feature_grid', 8), ('process', 11), ('metric_band', 15), ('editorial', 20), ('quote', 23), ('faq', 28), ('call_to_action', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 70, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 320, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 12, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 90}), 5: ('wagtail.blocks.TextBlock', (), {'max_length': 280}), 6: ('wagtail.blocks.StructBlock', [[('number', 3), ('title', 4), ('text', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'max_num': 6, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 2), ('features', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'max_num': 6, 'min_num': 2}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('steps', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 32}), 13: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 1)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'max_num': 4, 'min_num': 2}), 15: ('wagtail.blocks.StructBlock', [[('metrics', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('right', 'Right'), ('left', 'Left')]}), 20: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 16), ('body', 17), ('image', 18), ('image_side', 19)]], {}), 21: ('wagtail.blocks.TextBlock', (), {'max_length': 360}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 21), ('attribution', 1), ('role', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Questions, answered', 'max_length': 120}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 26: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 17)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'max_num': 10, 'min_num': 2}), 28: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 24), ('items', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'max_length': 130}), 30: ('wagtail.blocks.TextBlock', (), {'max_length': 320}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'A site path such as /employers/ or a full URL.', 'max_length': 240}), 33: ('wagtail.blocks.StructBlock', [[('label', 31), ('url', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('label', 31), ('url', 32)]], {'required': False}), 35: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 29), ('text', 30), ('primary', 33), ('secondary', 34)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_title', models.CharField(max_length=150)),
                ('hero_text', models.TextField(max_length=420)),
                ('primary_label', models.CharField(default='Book a conversation', max_length=50)),
                ('primary_url', models.CharField(default='/enquire/demo/', max_length=240)),
                ('secondary_label', models.CharField(default='See how it works', max_length=50)),
                ('secondary_url', models.CharField(default='/how-it-works/', max_length=240)),
                ('signal_label', models.CharField(default="Built for Malawi's private sector", max_length=80)),
                ('body', wagtail.fields.StreamField([('feature_grid', 8), ('process', 11), ('metric_band', 15), ('editorial', 20), ('quote', 23), ('faq', 28), ('call_to_action', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 70, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 320, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 12, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 90}), 5: ('wagtail.blocks.TextBlock', (), {'max_length': 280}), 6: ('wagtail.blocks.StructBlock', [[('number', 3), ('title', 4), ('text', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'max_num': 6, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 2), ('features', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'max_num': 6, 'min_num': 2}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('steps', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 32}), 13: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 1)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'max_num': 4, 'min_num': 2}), 15: ('wagtail.blocks.StructBlock', [[('metrics', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('right', 'Right'), ('left', 'Left')]}), 20: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 16), ('body', 17), ('image', 18), ('image_side', 19)]], {}), 21: ('wagtail.blocks.TextBlock', (), {'max_length': 360}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 21), ('attribution', 1), ('role', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Questions, answered', 'max_length': 120}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 26: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 17)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'max_num': 10, 'min_num': 2}), 28: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 24), ('items', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'max_length': 130}), 30: ('wagtail.blocks.TextBlock', (), {'max_length': 320}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'A site path such as /employers/ or a full URL.', 'max_length': 240}), 33: ('wagtail.blocks.StructBlock', [[('label', 31), ('url', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('label', 31), ('url', 32)]], {'required': False}), 35: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 29), ('text', 30), ('primary', 33), ('secondary', 34)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InsightIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, max_length=420)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InsightPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField()),
                ('summary', models.TextField(max_length=320)),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('feature_grid', 8), ('process', 11), ('metric_band', 15), ('editorial', 20), ('quote', 23), ('faq', 28), ('call_to_action', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 70, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 320, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 12, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 90}), 5: ('wagtail.blocks.TextBlock', (), {'max_length': 280}), 6: ('wagtail.blocks.StructBlock', [[('number', 3), ('title', 4), ('text', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'max_num': 6, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('intro', 2), ('features', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'max_num': 6, 'min_num': 2}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('steps', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 32}), 13: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 1)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'max_num': 4, 'min_num': 2}), 15: ('wagtail.blocks.StructBlock', [[('metrics', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('right', 'Right'), ('left', 'Left')]}), 20: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 16), ('body', 17), ('image', 18), ('image_side', 19)]], {}), 21: ('wagtail.blocks.TextBlock', (), {'max_length': 360}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 21), ('attribution', 1), ('role', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Questions, answered', 'max_length': 120}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 26: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 17)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'max_num': 10, 'min_num': 2}), 28: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 24), ('items', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'max_length': 130}), 30: ('wagtail.blocks.TextBlock', (), {'max_length': 320}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'A site path such as /employers/ or a full URL.', 'max_length': 240}), 33: ('wagtail.blocks.StructBlock', [[('label', 31), ('url', 32)]], {}), 34: ('wagtail.blocks.StructBlock', [[('label', 31), ('url', 32)]], {'required': False}), 35: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 29), ('text', 30), ('primary', 33), ('secondary', 34)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomeProofPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=36)),
                ('label', models.CharField(max_length=150)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_points', to='pages.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
