# Generated by Django 5.2.17 on 2026-08-24 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CONTACT', 'General contact'), ('DEMO', 'Book a conversation'), ('EMPLOYER', 'Employer application'), ('PROVIDER', 'Financial provider application'), ('COMPLAINT', 'Complaint or correction')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('organisation', models.CharField(blank=True, max_length=180)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('licence_reference', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('request_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status', 'created_at'], name='enquiries_e_kind_b6dc76_idx')],
            },
        ),
    ]
